services:
  client:
    build: ./client
    container_name: client_c
    ports:
      - 5173:5173
    depends_on:
      - server
    networks:
      - cengineers3-network

  server:
    build: ./server
    container_name: server_c
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo
    networks:
      - cengineers3-network

  redis:
    image: redis
    container_name: redis_c
    ports:
      - 6379:6379
    networks:
      - cengineers3-network

  mongo:
    image: mongo
    container_name: mongo_c
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - cengineers3-network

networks:
  cengineers3-network:
    driver: bridge

volumes:
  mongo-data:
