name: Deploy Client to gh-pages

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      # Step 2.1: Install pnpm global
      - name: Install dependencies in client folder
        working-directory: ./client
        run: npm install -g pnpm

      # Step 3: Navigate to client folder and install dependencies
      - name: Install dependencies in client folder
        working-directory: ./client
        run: pnpm install

      # Step 4: Run Unit Tests (if applicable) in client folder
      - name: Run Unit Tests in client folder
        working-directory: ./client
        run: pnpm run test:ci

      # Step 5: Build project in client folder
      - name: Build project in client folder
        working-directory: ./client
        run: pnpm run build:gh-pages

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          publish_dir: ./client/docs/browser
          publish_branch: gh-pages
